### ISSUE TITLE
Cannot delopy to openshift

### ISSUE THREAD

**Issue by tvvocold** [NodeBB/nodebb-chinese-simplified#1]
Got 503 error after i follow every step in the [doc](https://docs.nodebb.org/zh_CN/latest/installing/cloud/openshift.html)

**Comment by tvvocold** [comment]
FYI: the setup seems don't ask for nodejs Port number (8080) or IP or Hostname to bind to.
log here: http://p.fdzh.org/paste/QXakGVOq

**Comment by tvvocold** [comment]
and $./nodebb log:
[cluster] Spinning up another process...
25/2 05:58 [408221] - info: Time: Wed Feb 25 2015 05:58:09 GMT-0500 (EST)
25/2 05:58 [408221] - info: Initializing NodeBB v0.7.0-dev
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
25/2 05:58 [408221] - info: Enabling 'trust proxy'
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.

Seems like it don't need to paste the passwd for redis either...
But i re-setup & restart it still got 503...how to fix?

**Comment by julianlam** [comment]
This repository should not have an issue tracker, sorry. Please post again here: https://community.nodebb.org
